import { Glob } from "bun";
import { parse as parseYaml } from "yaml";

const briefGlob = new Glob("projects/smart-permission-tickets/briefs/p*.md");
const briefs: Array<{
  frontmatter: Record<string, unknown>;
  body: string;
  filename: string;
}> = [];

for await (const path of briefGlob.scan(".")) {
  const content = await Bun.file(path).text();

  // Parse frontmatter between --- delimiters
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!fmMatch) {
    console.warn(`Skipping ${path}: no frontmatter found`);
    continue;
  }

  const frontmatter = parseYaml(fmMatch[1]);
  const body = fmMatch[2].trim();
  const filename = path.split("/").pop()!;

  briefs.push({ frontmatter, body, filename });
}

// Sort by ID
briefs.sort((a, b) =>
  (a.frontmatter.id as string).localeCompare(b.frontmatter.id as string)
);

const digest = await Bun.file("projects/smart-permission-tickets/briefs/digest.md").text();
const methodology = await Bun.file("projects/smart-permission-tickets/briefs/methodology.md").text();
const taxonomy = JSON.parse(
  await Bun.file("projects/smart-permission-tickets/briefs/tag-taxonomy.json").text()
);

const output = `// AUTO-GENERATED by build.ts — do not edit manually
import type { Brief, Taxonomy } from "./types";

export const briefs: Brief[] = ${JSON.stringify(briefs, null, 2)};

export const digest: string = ${JSON.stringify(digest)};

export const methodology: string = ${JSON.stringify(methodology)};

export const taxonomy: Taxonomy = ${JSON.stringify(taxonomy, null, 2)};
`;

await Bun.write("src/data.ts", output);
console.log(`Generated src/data.ts with ${briefs.length} briefs`);
